[workspace]
members = [
    "lsusb"
]

resolver = "3"

[workspace.dependencies]
anyhow = { version = "1.0.100" }
env_logger = { version = "0.11.8" }
futures-lite = { version = "2.6.1" }
log = { version = "0.4.28" }
nusb = { version = "0.2.1" }
